services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexhacksbot
    env_file:
      - .env
    volumes:
      - ./attendees.csv:/app/attendees.csv:ro
    restart: always
